#pragma once
#include <windows.h>
#ifndef MYFONT
#define MYFONT
HFONT hFont22 = CreateFont(
	22, 0, 0, 0, FW_BOLD, FALSE, FALSE, FALSE,
	SHIFTJIS_CHARSET, OUT_DEFAULT_PRECIS,
	CLIP_DEFAULT_PRECIS, DEFAULT_QUALITY,
	VARIABLE_PITCH | FF_ROMAN, TEXT("‚½‚¢‚Õ")
);
HFONT hFont20 = CreateFont(
	20, 0, 0, 0, FW_BOLD, FALSE, TRUE, FALSE,
	SHIFTJIS_CHARSET, OUT_DEFAULT_PRECIS,
	CLIP_DEFAULT_PRECIS, DEFAULT_QUALITY,
	VARIABLE_PITCH | FF_ROMAN, TEXT("‚½‚¢‚Õ")
);
#endif // !MYFONT

